shopifyAccessToken = "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"
shopifyStoreName = "zendesk-integration-tutorial"
zendeskUsername = "mkt.sampath97@gmail.com"
zendeskPassword = "Qwe@123"
zendeskSubDomain= "wda2720"

